-- =====================================================
-- Hospital Management System — Additional DB Setup
-- Run this in SQL*Plus AFTER your existing tables
-- =====================================================

-- BILLING table (not in original schema)
CREATE TABLE BILLING (
    BILL_ID         NUMBER PRIMARY KEY,
    APPOINTMENT_ID  NUMBER REFERENCES APPOINTMENT(APPOINTMENT_ID),
    PATIENT_ID      NUMBER REFERENCES PATIENT(PATIENT_ID),
    TOTAL_AMOUNT    NUMBER(10,2),
    PAYMENT_STATUS  VARCHAR2(20) DEFAULT 'Unpaid',
    PAYMENT_METHOD  VARCHAR2(30),
    GENERATED_AT    DATE DEFAULT SYSDATE
);

-- =====================================================
-- SEQUENCES for auto-increment IDs
-- Only create if you don't already have them
-- =====================================================
CREATE SEQUENCE PATIENT_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE DOCTOR_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE STAFF_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE APPOINTMENT_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE PRESCRIPTION_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE BILLING_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE DEPARTMENT_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE ROOM_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE AVAILABILITY_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE STAFF_SHIFT_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE USER_SEQ START WITH 100 INCREMENT BY 1;

COMMIT;
